log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 10
batch_size: 8
pretrained_model: "/kaggle/working/SwaraASR/model/epoch_00080.pth"
train_data: "/kaggle/working/SwaraASR/Data/Full_data/train_list.txt"
val_data: "/kaggle/working/SwaraASR/Data/Full_data/val_list.txt"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 80
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0005
